### ISSUE TITLE
HTTP 403: API rate limit exceeded running `apply.pl`: There is an error while trying to accept suggestions

### ISSUE THREAD

**Issue by skanda890** [check-spelling/check-spelling#67]
There is an error while trying to accept suggestions.
![image](https://github.com/user-attachments/assets/b57c231f-c059-436e-9070-c4af0edf2a09)

**Comment by jsoref** [comment]
Hmmm... this was from:
https://github.com/Microsoft/winget-cli/actions/runs/9925258973#summary-27417477841

The version deployed in winget-cli is:
https://github.com/check-spelling/check-spelling/blob/d7cd2973c513e84354f9d6cf50a6417a628a78ce/apply.pl#L244-L245

There's a PR that would upgrade it to:
https://github.com/check-spelling/check-spelling/blob/00c989c97749eb0cb2d256bdc55ac61b0096c6d3/apply.pl#L378-L379

Can you try:
```
curl -s -S -L 'https://raw.githubusercontent.com/check-spelling/check-spelling/v0.0.22/apply.pl' |
perl - 'https://github.com/microsoft/winget-cli/actions/runs/9925258973/attempts/1'
```

That would give us the actual error. -- Please copy its output here.

If that doesn't work, the latest prerelease has additional logic, so I'd love to know if it works better...

https://github.com/check-spelling/check-spelling/blob/1aa270182840daf5e4bf0be91af8e2ca84d5ff96/apply.pl#L410-L411

try:
```
curl -s -S -L 'https://raw.githubusercontent.com/check-spelling/check-spelling/prerelease/apply.pl' |
perl - 'https://github.com/microsoft/winget-cli/actions/runs/9925258973/attempts/1'
```

And copy its output as well. 

Thanks!

**Comment by skanda890** [comment]
curl -s -S -L 'https://raw.githubusercontent.com/check-spelling/check-spelling/v0.0.22/apply.pl' |
perl - 'https://github.com/microsoft/winget-cli/actions/runs/9925258973/attempts/1':

```text
$ curl -s -S -L 'https://raw.githubusercontent.com/check-spelling/check-spelling/v0.0.22/apply.pl' |
perl - 'https://github.com/microsoft/winget-cli/actions/runs/9925258973/attempts/1'
apply.pl: Unknown error, please file a bug to https://github.com/check-spelling/check-spelling/issues/new
error fetching artifacts: HTTP 403: API rate limit exceeded for user ID 99239826. If you reach out to GitHub Support for help, please include the request ID 6826:131554:814053:854C06:6693C77E and timestamp 2024-07-14 12:41:34 UTC. (https://api.github.com/repos/microsoft/winget-cli/actions/runs/9925258973/artifacts?per_page=100)
```

curl -s -S -L 'https://raw.githubusercontent.com/check-spelling/check-spelling/prerelease/apply.pl' |
perl - 'https://github.com/microsoft/winget-cli/actions/runs/9925258973/attempts/1':
```text
$ curl -s -S -L 'https://raw.githubusercontent.com/check-spelling/check-spelling/prerelease/apply.pl' |
perl - 'https://github.com/microsoft/winget-cli/actions/runs/9925258973/attempts/1'
apply.pl: Unknown error, please file a bug to https://github.com/check-spelling/check-spelling/issues/new
error fetching artifacts: HTTP 403: API rate limit exceeded for user ID 99239826. If you reach out to GitHub Support for help, please include the request ID 47FA:169F21:8798C:8B378:6693C813 and timestamp 2024-07-14 12:44:03 UTC. (https://api.github.com/repos/microsoft/winget-cli/actions/runs/9925258973/artifacts?per_page=100)
```

**Comment by jsoref** [comment]
Wow. I certainly wasn't expecting to see that error. 

I can add in some rate limiting handling.

Do you have any idea why you'd possibly hit a rate limit? They usually allow quite a bit of API capacity.

**Comment by skanda890** [comment]
Fixed

**Comment by jsoref** [comment]
hmm... I still don't understand what happened... I can see your pull request, but did you run apply many times in a short interval?

**Comment by skanda890** [comment]
Think so.

**Comment by skanda890** [comment]
Now it works.

**Comment by jsoref** [comment]
ok. I wonder if you were using VSCode (maybe with the [SARIF viewer](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer) extension)?

Something (probably not apply.pl) is likely to have burned through your api call limit -- if you were curious (I would be if it were me, and I am as a downstream victim), you could open a ticket with https://support.github.com/contact/bug-report and ask them for a summary/list of the api calls that lead to hitting the token limit. In my shoes, I'd let the vendor who consumed most of the tokens know (in addition to letting the one that hit the limit, which you did, thanks).

**Comment by jsoref** [comment]
https://github.com/check-spelling/check-spelling/releases/v0.0.26 should improve this.
